[0m17:52:45.022617 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7242c7834ee0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7242c67ee320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7242c67ee2c0>]}


============================== 17:52:45.024948 | dce18afc-5d67-4d67-8d20-a11fb8025472 ==============================
[0m17:52:45.024948 [info ] [MainThread]: Running with dbt=1.9.2
[0m17:52:45.025553 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/vscode/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt docs serve', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:52:45.026046 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-tammikuu/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:52:45.026858 [debug] [MainThread]: Resource report: {"command_name": "serve", "command_success": false, "command_wall_clock_time": 0.052544054, "process_in_blocks": "0", "process_kernel_time": 0.047985, "process_mem_max_rss": "86392", "process_out_blocks": "8", "process_user_time": 1.023686}
[0m17:52:45.027324 [debug] [MainThread]: Command `dbt docs serve` failed at 17:52:45.027222 after 0.05 seconds
[0m17:52:45.027708 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7242c7834ee0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7242c67ee2c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7242c67ee3b0>]}
[0m17:52:45.028083 [debug] [MainThread]: Flushing usage events
[0m17:52:45.376843 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:50:43.958414 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d83fe460f70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d83ff28a3b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d83ff28a350>]}


============================== 09:50:43.962431 | 3d461ba6-f286-4edc-a1ac-444a68ed1a7f ==============================
[0m09:50:43.962431 [info ] [MainThread]: Running with dbt=1.9.2
[0m09:50:43.963090 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m09:50:43.963594 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-tammikuu/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m09:50:43.965430 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.06480746, "process_in_blocks": "59304", "process_kernel_time": 0.144207, "process_mem_max_rss": "86164", "process_out_blocks": "16", "process_user_time": 1.157669}
[0m09:50:43.965937 [debug] [MainThread]: Command `dbt run` failed at 09:50:43.965829 after 0.07 seconds
[0m09:50:43.966319 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d83fe460f70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d83ff28aa70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d83ff28a3b0>]}
[0m09:50:43.966740 [debug] [MainThread]: Flushing usage events
[0m09:50:44.329258 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:00:29.654737 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x774318e10f40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x774319c6e350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x774319c6e2f0>]}


============================== 14:00:29.657802 | 889be566-639f-4a79-bf8c-9eab5226b2db ==============================
[0m14:00:29.657802 [info ] [MainThread]: Running with dbt=1.9.2
[0m14:00:29.658521 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run -m stg_coffee_shop__products', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:00:29.659068 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-tammikuu/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:00:29.660001 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.055165548, "process_in_blocks": "8", "process_kernel_time": 0.056033, "process_mem_max_rss": "86268", "process_out_blocks": "8", "process_user_time": 1.066646}
[0m14:00:29.660511 [debug] [MainThread]: Command `dbt run` failed at 14:00:29.660396 after 0.06 seconds
[0m14:00:29.660895 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x774318e10f40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x774319c6ea10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x774319c6e350>]}
[0m14:00:29.661314 [debug] [MainThread]: Flushing usage events
[0m14:00:29.999135 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m06:41:52.628299 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d1e435a8fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d1e444023b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d1e44402350>]}


============================== 06:41:52.632400 | e4e7dba0-1692-4beb-af78-3d02a52ec93a ==============================
[0m06:41:52.632400 [info ] [MainThread]: Running with dbt=1.9.2
[0m06:41:52.633073 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m06:41:52.633644 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-tammikuu/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m06:41:52.635674 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.057744402, "process_in_blocks": "60704", "process_kernel_time": 0.157558, "process_mem_max_rss": "85704", "process_out_blocks": "16", "process_user_time": 1.153089}
[0m06:41:52.636158 [debug] [MainThread]: Command `dbt run` failed at 06:41:52.636047 after 0.06 seconds
[0m06:41:52.636570 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d1e435a8fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d1e44402a70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7d1e444023b0>]}
[0m06:41:52.636973 [debug] [MainThread]: Flushing usage events
[0m06:41:53.033860 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m05:49:37.736793 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74396d7b0f40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74396e62a230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74396e62a1d0>]}


============================== 05:49:37.746059 | 94f68707-8264-4573-9a31-3cbb184e78b7 ==============================
[0m05:49:37.746059 [info ] [MainThread]: Running with dbt=1.9.2
[0m05:49:37.747085 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/vscode/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt deps', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m05:49:37.748278 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /workspaces/ae-club-tammikuu/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m05:49:37.787988 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.45589295, "process_in_blocks": "70472", "process_kernel_time": 0.360755, "process_mem_max_rss": "86000", "process_out_blocks": "8", "process_user_time": 1.543287}
[0m05:49:37.788624 [debug] [MainThread]: Command `dbt deps` failed at 05:49:37.788471 after 0.46 seconds
[0m05:49:37.789098 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74396d7b0f40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74396e62a9b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74396e62a470>]}
[0m05:49:37.791405 [debug] [MainThread]: Flushing usage events
[0m05:49:38.170105 [debug] [MainThread]: An error was encountered while trying to flush usage events
